query GetAssetSpecific($asset: String!, $timeFilter: BigInt!) {
  dataFeeds(first: 1000, where: { asset: $asset, denomination: "USD" }) {
    id
    phaseId
    live
    decimals
    prices(first: 1000, orderBy: roundId, orderDirection: asc, where: { blockTimestamp_gte: $timeFilter }) {
      id
      price
      roundId
      blockTimestamp
      blockNumber
    }
  }
}
